apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gng-frontend
  name: gng-frontend
  namespace: griot-grits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gng-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gng-frontend
    spec:
      containers:
      - image: quay.io/cpigues/gng-frontend:v1.0.0
        imagePullPolicy: Always
        name: gng-frontend
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30