apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gng-frontend
  name: gng-frontend
  namespace: griot-grits
spec:
  host: gng-frontend-griot-grits.apps.ocp-test.nerc.mghpcc.org
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gng-frontend
    weight: 100
  wildcardPolicy: None