apiVersion: v1
kind: Service
metadata:
  labels:
    app: gng-frontend
  name: gng-frontend
  namespace: griot-grits
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gng-frontend
  sessionAffinity: None
  type: ClusterIP
