apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whisper-api
  name: whisper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whisper-api
    spec:
      containers:
      - name: whisper-api
        image: docker.io/onerahmet/openai-whisper-asr-webservice:latest-gpu
        env:
          - name: ASR_ENGINE
            value: openai_whisper
          - name: ASR_MODEL
            value: tiny.en
          - name: ASR_DEVICE
            value: cuda
          - name: ASR_MODEL_PATH
            value: /tmp/.cache
          - name: MODEL_IDLE_TIMEOUT
            value: "0"
          - name: TRANSFORMERS_CACHE
            value: /tmp/huggingface/hub
          - name: MPLCONFIGDIR
            value: /tmp/.config
        resources:
          requests:
            memory: "6Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "12Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          protocol: TCP
      tolerations:
      - key: nvidia.com/gpu.product
        operator: Equal
        value: NVIDIA-A100-SXM4-40GB
        effect: NoSchedule
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
